version: "3.9"

services:
  back-app:
    container_name: back-app
    build:
      context: .
    env_file:
      - .env
    networks:
      - site
    restart: unless-stopped

networks:
  site:
    driver: bridge
    external: true
