version: "3.9"

services:
  back-app:
    container_name: back-app
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm i && npx prisma generate && npm run postprisma:generate && npm run start"
    networks:
      - site
    restart: unless-stopped

networks:
  site:
    driver: bridge
    external: true
