// This file was auto-generated by prisma-generator-typescript-interfaces

export type KycStatus = "CREATED" | "COMPLETED" | "APPROVED" | "DECLINED";

export type PropertyStatus = "COMING_SOON" | "ACTIVE" | "SOLD_OUT" | "COMPLETED";

export type PropertyTierType = "PLATINUM" | "RUBY" | "DIAMOND";

export interface User {
  id: string;
  cognitoId: string;
  email: string;
  referralLink: string | null;
  kycStatus: KycStatus | null;
  kycProviderId: string | null;
  kycCompletedAt: Date | null;
  createdAt: Date;
  transactions?: TokenTransaction[];
}

export interface Property {
  id: string;
  contractAddress: string;
  title: string;
  status: PropertyStatus;
  createdAt: Date;
  description: string | null;
  address: string | null;
  media: JsonValue | null;
  tiers?: PropertyTier[];
}

export interface PropertyTier {
  id: string;
  propertyId: string;
  type: PropertyTierType;
  price: number;
  totalSupply: number;
  benefits: JsonValue | null;
  property?: Property;
  transactions?: TokenTransaction[];
}

export interface TokenTransaction {
  id: string;
  userId: string;
  tierId: string;
  tokensAmount: number;
  userAddress: string;
  contractAddress: string;
  txHash: string;
  paymentAmount: number;
  createdAt: Date;
  user?: User;
  tier?: PropertyTier;
}

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
