#!/usr/bin/env sh

# Пропускаем при merge/rebase
if [ -f ".git/MERGE_HEAD" ] || [ -f ".git/rebase-merge" ]; then
  echo "➡️ Merge/rebase detected - skipping tests"
  exit 0
fi

# echo "🧪 Running tests..."
# npm run test:unit || exit 1
