name: Publish Types

on:
  push:
    branches: [main]
    paths:
      - "prisma/schema.prisma"
      - "types/package.json"
    paths-ignore:
      - "**/package-lock.json" # Игнорируем изменения в lock-файле

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Полный history для корректной работы с версиями

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com

      - name: Install and publish
        run: |
          cd types
          npm ci --ignore-scripts
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
